spring.application.name=rtdias3d

server.port=${PORT:8080}

spring.datasource.url=jdbc:mysql://${DB_HOST:centerbeam.proxy.rlwy.net}:${DB_PORT:3306}/${DB_NAME:railway}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:hYFjbgDSOfsnoZruvaWhOwiCAUyvjGSt}


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_FORMAT_SQL:false}

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


admin.chave-secreta=${ADMIN_SECRET:}
jwt.secret=${JWT_SECRET:}
jwt.expiration=${JWT_EXPIRATION:86400000}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.health.db.enabled=true
